version: '3.8'

services: 
  cms:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8075:80
    networks:
      - db

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    networks:
      - db

networks:
  db:
    driver: bridge
  
volumes:
  mariadb-data:
